version: "3"

services: 
  app:
    container_name: blog-api
    build: 
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    env_file: .env.dev
    depends_on: 
      - database
    networks: 
      - blognetwork
  database:
    container_name: blog-db
    image: postgres
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr3s
      - POSTGRES_DB=blog
    volumes: 
      - pgdata:/data/postgres
    networks: 
      - blognetwork

volumes:
  pgdata:
    driver: local

networks: 
  blognetwork:
    driver: bridge
    